### ISSUE TITLE
Error occurs at recent TensorFlow 0.12

### ISSUE THREAD

**Issue by wsjeon** [miyosuda/async_deep_reinforce#22]
Hi. I got the following message. I use TF 0.12.

File "/home/itl/async_deep_reinforce/a3c_training_thread.py", line 42, in __init__
    var_refs = [v.ref() for v in self.local_network.get_vars()]
AttributeError: 'Variable' object has no attribute 'ref'

I found that 'ref' is changed to 'read_value' in the recent updates. 
(http://stackoverflow.com/questions/40901391/what-is-the-alternative-of-tf-variable-ref-in-tensorflow-version-0-12)

Thank you.

-------------------------------------------------------

After addressing the upper issue,  I got another error.

WARNING:tensorflow:tf.op_scope(values, name, default_name) is deprecated, use tf.name_scope(name, default_name, values)
Traceback (most recent call last):
  File "a3c.py", line 70, in <module>
    device = device)
  File "/home/itl/async_deep_reinforce/a3c_training_thread.py", line 53, in __init__
    self.gradients )
  File "/home/itl/async_deep_reinforce/rmsprop_applier.py", line 103, in apply_gradients
    clipped_accum_grad = tf.clip_by_norm(accum_grad, self._clip_norm)
  File "/home/itl/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/clip_ops.py", line 96, in clip_by_norm
    t = ops.convert_to_tensor(t, name="t")
  File "/home/itl/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 669, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/itl/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/itl/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/itl/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 360, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

I think something wrong in RMSoptimizer for latest TF.

**Comment by miyosuda** [comment]
Thank you for pointing out. This repo was tested with TF r0.10, and is not compatible with r0.12 now.

Recently @babaktr send me PR with r0.10 -> r.0.12 upgrading in another project which is using same code.

https://github.com/miyosuda/unreal/pull/2/commits/78b8da8852dfa39de79d3e8c3fbc43a0961e5545

Soon I'm going to upgrade this repo to r0.12 too.

**Comment by wsjeon** [comment]
Thank you for your useful comments :)
