### ISSUE TITLE
Variable net_-1/BasicLSTMCell/Linear/Matrix does not exist, or was not created with tf.get_variable().

### ISSUE THREAD

**Issue by nanxintin** [miyosuda/async_deep_reinforce#32]
Hi @miyosuda ,
Thank you for sharing the code.
When I tried to run the code, I came across some problem.
'''
Traceback (most recent call last):
  File "a3c.py", line 50, in <module>
    global_network = GameACLSTMNetwork(ACTION_SIZE, -1, device)
  File "/home/lab/sk/a3c-new/async_deep_reinforce/game_ac_network.py", line 218, in __init__
    self.W_lstm = tf.get_variable("BasicLSTMCell/Linear/Matrix")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 988, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 890, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 348, in get_variable
    validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 333, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 657, in _get_single_variable
    "VarScope?" % name)
ValueError: Variable net_-1/BasicLSTMCell/Linear/Matrix does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?
'''
I have tf1.0 installed, and I have trouble debugging it out. I would appreciate it very much if you can help me.

**Comment by marcushill** [comment]
Not sure if you've figured this out already, but I think it might be useful for anyone else running into this. I'm on tf1.0 with Python 3.5.

This worked for me:
```python
self.W_lstm = tf.get_variable("basic_lstm_cell/weights")
self.b_lstm = tf.get_variable("basic_lstm_cell/biases")
```

It looks like they changed the names of some variables created by `tf.contrib.rnn.BasicLSTMCell`. 

I found the names by doing this and playing with the strings until it worked. 
```python
for x in tf.get_collection(tf.GraphKeys.VARIABLES):
    print(x.name)
```

**Comment by nanxintin** [comment]
Hi @marcushill ,
Thank you for your reply. and your solution works for me.
This will be useful for anyone else running the code with tf1.0 and python3.5.
Thanks again.

**Comment by kmcnayr** [comment]
This needs to be updated again per the latest release notes: https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md

I successfully ran a3c.py by substituting "kernel" for "weights" and "bias" for "biases"
